language: php

php: [5.4, 5.5, 5.6, 7.0, hhvm]

matrix:
    include:
        # Test against librabbitmq cutting-edge
        - { php: 5.5, env: LIBRABBITMQ_VERSION=master }
        - { php: 5.4, env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' }
    allow_failures:
        - php: hhvm

services: [rabbitmq]

script: ./bin/phpunit

before_script:
  - sh -c 'if [ "$LIBRABBITMQ_VERSION" != "" ]; then ./tests/bin/install_librabbitmq.sh; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension=amqp.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; fi;'
  - composer selfupdate
  - composer update --prefer-source -n $COMPOSER_FLAGS
  - sh -c "sudo ./tests/bin/prepare_rabbit.sh"

script: vendor/bin/phpunit
